# Generated by Django 5.1.6 on 2025-03-01 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teachersettings_class_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersettings',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher'),
        ),
    ]
