# Generated by Django 5.1.6 on 2025-03-01 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_teachersettings_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='classactivity',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.class'),
        ),
    ]
